import type { Metadata } from "next";
import { Montserrat, Philosopher } from "next/font/google";
import "./globals.scss";

// Montserrat será nuestra fuente principal
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat", // Exportamos la variable CSS
});

// Philosopher será para títulos y elementos destacados
const philosopher = Philosopher({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-philosopher", // Exportamos la variable CSS
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${montserrat.variable} ${philosopher.variable}`} >
      <body  className={montserrat.className} >
        {children}
      </body>
    </html>
  );
}
